import asyncio
from datetime import datetime, timedelta
from typing import Literal, Optional
import uuid
from Logger import logger
from src.config import config
from src.taskscheduling.services import putting_task,check_task_id_exits
from .celery import app
from ..email.email_read import read_emails
from ..email.email_Send import send_email
from langchain_ollama import ChatOllama
from langchain_core.prompts import PromptTemplate
from pydantic import BaseModel, Field
from ..taskscheduling.schema import Response
from ..taskscheduling.services import update_tasks_feild
from ..DB.postgres import PoolManager

class task_payload(BaseModel):
    recipent_email: str = Field(..., description="The email address of the recipient.")
    subject: str = Field(..., description="The subject of the email.")
    body_summary: str = Field(..., description="The body content small summary of the email.")
    priority: str = Field(..., description="The urgency level of the email (e.g., low, medium, high).")
    received_date: str = Field(..., description="The date and time the email was sent. This will be format in datatime object.")
    Deadline_date: Optional[str] = Field(..., description="The important date and time related to the email, such as a deadline or event date. This field is optional and may be null if not applicable. This will be format in datatime object.")
    task_type: Literal["email_send", "notify_user","None"] = Field(..., description="The type of task to be performed ignore if it a advertisement email from linkedin(e.g., email_send, email_fetch, notify_user,None).")
    schedule_type: Literal["one_time", "interval"] = Field(..., description="The scheduling type of the task (e.g., one_time, interval).")
class llm_response(BaseModel):
    message: str = Field(..., description="The response message generated by the language model based on the provided task payload. This message may contain information, instructions, or any relevant content related to the task being executed.")
    payload: list[task_payload] = Field(default_factory=list, description="A list of task payloads containing the necessary information for executing the task. The structure of each payload will depend on the task type and may include fields such as recipient_email, subject, body_summary, priority, received_date, and Deadline_date.")

prompt = PromptTemplate.from_template("""
You are a task scheduler assistant. Analyze the emails below and extract only actionable tasks.
Return a JSON object with two fields: "message" (a brief summary string) and "payload" (an array of task objects).
Output ONLY valid JSON — no explanation, no markdown, no preamble.

INPUT:
{input_text}

TODAY'S DATE (UTC): {current_date}

OUTPUT SCHEMA:
{{
  "message": "<brief overall summary of what was processed>",
  "payload": [
    {{
      "recipent_email": "<sender's email address>",
      "subject": "<email subject line>",
      "body_summary": "<one specific sentence: WHO needs to do WHAT and by WHEN>",
      "priority": "low" | "medium" | "high",
      "received_date": "<ISO 8601 UTC datetime the email was received>",
      "Deadline_date": "<ISO 8601 UTC datetime of deadline/event, or null>",
      "task_type": "email_send" | "notify_user" | "None",
      "schedule_type": "one_time" | "interval"
    }}
  ]
}}

FIELD RULES:

task_type:
  "email_send"   → a reply, follow-up, or new email needs to be composed and sent
  "notify_user"  → user needs to be alerted about something (meeting, deadline, reminder)
  "None"         → advertisements, newsletters, LinkedIn promotions, no-reply blasts — SKIP these entirely, do not include in payload

priority:
  "high"   → urgent, time-sensitive, explicitly marked important, or deadline within 24h
  "medium" → normal importance, response expected but not immediately
  "low"    → FYI, low-stakes, no deadline signal

Deadline_date:
  Extract from the email body if a specific date/time is mentioned.
  If relative (e.g. "by Friday", "in 3 days"), resolve against TODAY'S DATE.
  Set to null if no deadline is stated or implied.

schedule_type:
  "one_time"  → task needs to happen once (send a reply, attend a meeting)
  "interval"  → task recurs (daily standups, weekly reports, recurring reminders)

body_summary:
  One sentence. Be specific.
  Bad:  "Send email"
  Good: "Reply to John at john@acme.com confirming attendance for the 3pm meeting on June 5"

IMPORTANT:
- Do NOT include promotional, advertising, or LinkedIn notification emails in the payload.
- If no actionable emails exist, return an empty payload array [].
- All datetime strings must be in ISO 8601 UTC format: "YYYY-MM-DDTHH:MM:SSZ"
""")

def make_unique_id(message_id,task_type)->uuid.UUID:
    return uuid.uuid5(uuid.NAMESPACE_DNS, f"{message_id}-{task_type}")

def handle_task(task_id):
    conn=PoolManager.get_sync_pool(config.URI)
    with conn.connection() as connection:
        dict_row= connection.execute("SELECT * FROM tasks WHERE task_id = %s", (task_id,))
    result= dict_row.fetchall()
    if not result:
        logger.error(f"Task with ID {task_id} not found.")
        return
    for row in result:
        task_type=row["task_type"] # type: ignore
        if task_type=="email_fetch":
            email_fetch()
        if task_type=="email_send":
            pass
        if task_type=="notify_user":
            pass
     
def email_fetch():
    llm = ChatOllama(model="ministral-3:8b", temperature=0, verbose=False)
    model = llm.with_structured_output(llm_response)
    try:
        started_at = datetime.now()
        scheduled_time = datetime.now()

        emails = asyncio.run(read_emails())
        if not emails:
            logger.info("No new emails.")
            return
        chain = prompt | model
        for msg_id, content in emails.items():
            logger.info(f"Processing email {msg_id} content: {content}")
            try:
                response = chain.invoke({
                    "input_text": content,   
                    "current_date": datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")
                })
                logger.info(f"LLM response for {msg_id}: {response}")

                for task in response.payload:  # type: ignore
                    if task.task_type == "None":
                        continue

                    payload = {
                        "recipient_email": task.recipent_email,
                        "subject": task.subject,
                        "body": task.body_summary,
                    }
                    task_response = Response(
                        task_id=make_unique_id(msg_id,task.task_type),
                        task_type=task.task_type,
                        status="pending",
                        priority=task.priority,
                        payload=payload,
                        result={},
                        schedule_type=task.schedule_type,
                        scheduled_time=scheduled_time,
                        interval_seconds=0,
                        next_run_time=scheduled_time,
                        started_at=started_at,
                        completed_at=datetime.now(),
                        retry_count=0,
                    )
                    putting_task(response=task_response)  

            except Exception as e:
                logger.exception(f"Error processing email {msg_id}: {e}")
                continue
    except Exception as e:
        logger.exception(f"Error in email_fetch: {e}")
        raise e